# Generated by Django 5.2.5 on 2025-09-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="slide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="slider/", verbose_name="عکس"
                    ),
                ),
                (
                    "img_url",
                    models.URLField(blank=True, null=True, verbose_name="لینک خارجی"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="فعال ؟ "),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
