# Generated by Django 5.2.5 on 2025-09-10 14:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "verbose_name": "دسته\u200cبندی",
                "verbose_name_plural": "دسته\u200cبندی\u200cها",
            },
        ),
        migrations.AlterModelOptions(
            name="products",
            options={"verbose_name": "محصول", "verbose_name_plural": "محصولات"},
        ),
        migrations.RemoveField(
            model_name="products",
            name="category",
        ),
        migrations.RemoveField(
            model_name="products",
            name="updated",
        ),
        migrations.AddField(
            model_name="category",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="products",
            name="categories",
            field=models.ManyToManyField(
                related_name="products",
                to="products.category",
                verbose_name="دسته\u200cبندی\u200cها",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                max_length=200, unique=True, verbose_name="نام دسته\u200cبندی"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(max_length=200, unique=True, verbose_name="اسلاگ"),
        ),
        migrations.AlterField(
            model_name="products",
            name="available",
            field=models.BooleanField(default=True, verbose_name="موجود است؟"),
        ),
        migrations.AlterField(
            model_name="products",
            name="description",
            field=models.TextField(blank=True, verbose_name="توضیحات"),
        ),
        migrations.AlterField(
            model_name="products",
            name="name",
            field=models.CharField(max_length=200, verbose_name="نام محصول"),
        ),
        migrations.AlterField(
            model_name="products",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="قیمت"
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="slug",
            field=models.SlugField(max_length=200, unique=True, verbose_name="اسلاگ"),
        ),
    ]
