# Generated by Django 6.0.6 on 2026-07-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_products_image_products_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
