# Generated by Django 5.2.5 on 2025-09-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="نام برند"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="brands/",
                        verbose_name="لوگو برند",
                    ),
                ),
                (
                    "logo_url",
                    models.URLField(
                        blank=True,
                        null=True,
                        verbose_name="آدرس لوگو (در صورت استفاده از URL)",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True, null=True, verbose_name="وب\u200cسایت رسمی برند"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال؟")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "برند",
                "verbose_name_plural": "برندها",
            },
        ),
    ]
