# Generated by Django 5.2.5 on 2025-09-11 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pages",
            name="url",
        ),
        migrations.AddField(
            model_name="pages",
            name="redirect_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="pages",
            name="slug",
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name="pages",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
