# Generated by Django 6.0.6 on 2026-07-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_headerlinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
